#Create a new post in the database#
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title":"first post",
    "description":"sdfkjsdlfkjsdflk"
}

###

#Get all the posts from the database
GET http://localhost:3000/posts
